import{Prisma}from"@/generated/prisma/client";import{getPrisma}from"@/lib/prisma";import type{RepairInput,ScheduleInput}from"./validation";
async function ownedHome(userId:string,homeId:string){return getPrisma().home.findFirst({where:{id:homeId,userId},select:{id:true,name:true}})}async function validItem(userId:string,homeId:string,itemId:string|null){return !itemId||Boolean(await getPrisma().homeItem.findFirst({where:{id:itemId,homeId,home:{userId}},select:{id:true}}))}
async function validRepair(userId:string,homeId:string,repairId:string|null){return !repairId||Boolean(await getPrisma().homeRepair.findFirst({where:{id:repairId,homeId,home:{userId}},select:{id:true}}))}
export async function listRepairs(userId:string,homeId:string){const home=await ownedHome(userId,homeId);if(!home)return null;return{home,items:await getPrisma().homeItem.findMany({where:{homeId},select:{id:true,name:true}}),repairs:await getPrisma().homeRepair.findMany({where:{homeId},include:{homeItem:{select:{name:true}}},orderBy:{repairDate:"desc"}})}}
export async function createRepair(userId:string,homeId:string,input:RepairInput){if(!await ownedHome(userId,homeId)||!await validItem(userId,homeId,input.homeItemId))return null;return getPrisma().$transaction(async tx=>{const repair=await tx.homeRepair.create({data:{homeId,homeItemId:input.homeItemId,type:input.type,title:input.title,description:input.description,repairDate:input.repairDate,cost:input.cost==null?null:new Prisma.Decimal(input.cost),companyName:input.companyName,nextCheckDate:input.nextCheckDate,memo:input.memo}});if(input.createSchedule&&input.nextCheckDate)await tx.homeSchedule.create({data:{homeId,homeItemId:input.homeItemId,repairId:repair.id,title:`${input.title} 다음 점검`,scheduledAt:input.nextCheckDate,type:"INSPECTION",memo:"수리·점검 기록에서 생성된 일정"}});return repair})}
export function getOwnedRepair(userId:string,homeId:string,id:string){return getPrisma().homeRepair.findFirst({where:{id,homeId,home:{userId}},include:{homeItem:{select:{id:true,name:true}}}})}
export async function updateRepair(userId:string,homeId:string,id:string,input:RepairInput){if(!await validItem(userId,homeId,input.homeItemId))return null;const result=await getPrisma().homeRepair.updateMany({where:{id,homeId,home:{userId}},data:{homeItemId:input.homeItemId,type:input.type,title:input.title,description:input.description,repairDate:input.repairDate,cost:input.cost==null?null:new Prisma.Decimal(input.cost),companyName:input.companyName,nextCheckDate:input.nextCheckDate,memo:input.memo}});return result.count?getOwnedRepair(userId,homeId,id):null}
export async function deleteRepair(userId:string,homeId:string,id:string){return(await getPrisma().homeRepair.deleteMany({where:{id,homeId,home:{userId}}})).count===1}
export async function listSchedules(userId:string,homeId:string){const home=await ownedHome(userId,homeId);if(!home)return null;return{home,items:await getPrisma().homeItem.findMany({where:{homeId},select:{id:true,name:true}}),schedules:await getPrisma().homeSchedule.findMany({where:{homeId},include:{homeItem:{select:{name:true}}},orderBy:{scheduledAt:"asc"}})}}
export async function createSchedule(userId:string,homeId:string,input:ScheduleInput){if(!await ownedHome(userId,homeId)||!await validItem(userId,homeId,input.homeItemId)||!await validRepair(userId,homeId,input.repairId))return null;return getPrisma().homeSchedule.create({data:{...input,homeId}})}
export function getOwnedSchedule(userId:string,homeId:string,id:string){return getPrisma().homeSchedule.findFirst({where:{id,homeId,home:{userId}},include:{homeItem:{select:{id:true,name:true}}}})}
export async function updateSchedule(userId:string,homeId:string,id:string,input:ScheduleInput){if(!await validItem(userId,homeId,input.homeItemId)||!await validRepair(userId,homeId,input.repairId))return null;const result=await getPrisma().homeSchedule.updateMany({where:{id,homeId,home:{userId}},data:input});return result.count?getOwnedSchedule(userId,homeId,id):null}
export async function deleteSchedule(userId:string,homeId:string,id:string){return(await getPrisma().homeSchedule.deleteMany({where:{id,homeId,home:{userId}}})).count===1}
export async function dashboardManagement(userId:string){const now=new Date(),soon=new Date(now.getTime()+7*86400000);const prisma=getPrisma();const[countItems,countRepairs,countSchedules,upcoming]=await Promise.all([prisma.homeItem.count({where:{home:{userId}}}),prisma.homeRepair.count({where:{home:{userId}}}),prisma.homeSchedule.count({where:{home:{userId},completed:false}}),prisma.homeSchedule.findMany({where:{home:{userId},completed:false,scheduledAt:{lte:soon}},orderBy:{scheduledAt:"asc"},take:6,include:{home:{select:{name:true}}}})]);return{countItems,countRepairs,countSchedules,upcoming,now}}
