import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { authOptions } from "@/lib/auth/options";
import { getCommunitySummary } from "@/lib/community/service";
import styles from "./community.module.css";
export const metadata:Metadata={title:"우리 아파트 커뮤니티 | 집갈피",robots:{index:false,follow:false}};
const categoryLabel={GENERAL:"자유게시판",QUESTION:"질문",INFO:"정보",LOST_AND_FOUND:"분실물"} as const;
const marketStatus={ACTIVE:"판매중",RESERVED:"예약중",COMPLETED:"거래완료",CANCELLED:"취소"} as const;
export default async function CommunityHome({params}:PageProps<"/apartments/[id]/community">){const session=await getServerSession(authOptions);if(!session?.user?.id)redirect("/login");const {id}=await params;const data=await getCommunitySummary(session.user.id,id);if(!data)notFound();const {apartment}=data.membership;return <main className={styles.page}><div className={styles.shell}><Link className={styles.back} href="/dashboard">← Dashboard</Link><section className={styles.hero}><div><p className={styles.eyebrow}>OUR APARTMENT</p><h1>{apartment.name}</h1><p>우리 아파트 커뮤니티</p></div><div className={styles.memberCount}>참여 회원 {data.memberCount.toLocaleString("ko-KR")}명</div></section><nav className={styles.tabs} aria-label="커뮤니티 메뉴"><Link className={styles.active} href={`/apartments/${id}/community`}>커뮤니티 홈</Link><Link href={`/apartments/${id}/community/posts`}>게시판</Link><Link href={`/apartments/${id}/marketplace`}>나눔/중고거래</Link></nav><section className={styles.section}><div className={styles.heading}><h2>최근 게시글</h2><Link className={styles.primary} href={`/apartments/${id}/community/posts/new`}>글쓰기</Link></div>{data.posts.length?<div className={styles.list}>{data.posts.map(post=><Link className={styles.listItem} href={`/apartments/${id}/community/posts/${post.id}`} key={post.id}><span className={styles.badge}>{categoryLabel[post.category]}</span><div><h2>{post.title}</h2><span className={styles.meta}>{post.authorMember.user.nickname} · 댓글 {post._count.comments}</span></div><time>{post.createdAt.toLocaleDateString("ko-KR")}</time></Link>)}</div>:<div className={styles.empty}>첫 게시글을 남겨 이웃과 이야기를 시작해보세요.</div>}</section><section className={styles.section}><div className={styles.heading}><h2>나눔/중고거래</h2><Link className={styles.primary} href={`/apartments/${id}/marketplace/new`}>물품 등록</Link></div>{data.marketplace.length?<div className={styles.grid}>{data.marketplace.map(item=><Link className={styles.card} href={`/apartments/${id}/marketplace/${item.id}`} key={item.id}><span className={styles.badge}>{item.type==="GIVEAWAY"?"나눔":marketStatus[item.status]}</span><h3>{item.title}</h3><strong className={styles.price}>{item.type==="GIVEAWAY"?"무료 나눔":`${item.price.toLocaleString("ko-KR")}원`}</strong><small>{item.sellerMember.user.nickname} · {item.createdAt.toLocaleDateString("ko-KR")}</small></Link>)}</div>:<div className={styles.empty}>아직 등록된 물품이 없습니다.</div>}</section><section className={styles.section}><div className={styles.heading}><h2>우리 아파트 소식</h2></div><div className={styles.notice}>공식 공지 기능은 준비 중입니다. 현재는 게시판의 ‘정보’ 카테고리에서 이웃과 소식을 나눌 수 있어요.</div></section><section className={styles.section}><p className={styles.eyebrow}>COMING NEXT</p><div className={styles.future}><span>공동구매</span><span>업체추천</span><span>분실물</span><span>투표</span></div></section></div></main>}
