import { getServerSession } from "next-auth";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AllHomesFilter } from "@/components/home/all-homes-filter";
import { RecordPageHeader } from "@/components/home/record-page-header";
import { authOptions } from "@/lib/auth/options";
import { derivedContractStatus, listAllContracts } from "@/lib/home-contract/service";
import styles from "@/app/items/items.module.css";
const types = { LEASE: "임대·전세", RENTAL: "렌탈", INSURANCE: "보험", INTERNET: "인터넷", SECURITY: "보안", MAINTENANCE: "유지관리", SUBSCRIPTION: "구독", OTHER: "기타" }; const statuses = { ACTIVE: "사용 중", EXPIRING: "만료 예정", EXPIRED: "만료", TERMINATED: "종료" };
export default async function ContractsPage({ searchParams }: { searchParams: Promise<{ homeId?: string | string[] }> }) { const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login"); const query = await searchParams; const requestedHomeId = typeof query.homeId === "string" ? query.homeId : undefined; const data = await listAllContracts(session.user.id, requestedHomeId); return <main className={styles.page}><div className={styles.shell}><RecordPageHeader eyebrow="ALL HOME CONTRACTS" title="계약" description="모든 집의 렌탈·보험·인터넷·주거 계약을 한곳에서 관리하세요." actionHref={data.homes.length ? "/contracts/new" : undefined} actionLabel="계약 등록" /><AllHomesFilter homes={data.homes} activeHomeId={data.homeId} basePath="/contracts" />{!data.homes.length ? <section className={styles.empty}><span>🏡</span><h2>먼저 주거공간을 등록해 주세요</h2><p>집을 등록하면 계약을 관리할 수 있습니다.</p><Link className={styles.primary} href="/home/new">내 집 등록하기</Link></section> : data.contracts.length ? <section className={styles.grid} aria-label="계약 목록">{data.contracts.map((contract) => { const state = derivedContractStatus(contract); return <Link className={styles.card} href={`/homes/${contract.homeId}/contracts/${contract.id}`} key={contract.id}><div className={styles.cardTop}><span className={styles.badge}>{types[contract.type]}</span><span className={styles.status}>{statuses[state]}</span></div><h2>{contract.title}</h2><p className={styles.homeName}><span>🏠</span>{contract.home.name}</p><p className={styles.meta}>{contract.endDate ? `${contract.endDate.toLocaleDateString("ko-KR")} 만료` : "종료일 미입력"}</p></Link>; })}</section> : <section className={styles.empty}><span>📝</span><h2>아직 등록된 계약이 없습니다</h2><p>주거·렌탈·보험 계약의 중요한 날짜를 관리해보세요.</p><Link className={styles.primary} href="/contracts/new">첫 계약 등록</Link></section>}</div></main>; }
