import { getServerSession } from "next-auth";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AllHomesFilter } from "@/components/home/all-homes-filter";
import { RecordPageHeader } from "@/components/home/record-page-header";
import { authOptions } from "@/lib/auth/options";
import { listAllSchedules } from "@/lib/home-management/service";
import styles from "@/app/items/items.module.css";
const labels = { INSPECTION: "점검", WARRANTY: "보증", REPAIR: "수리", CONTRACT: "계약", PAYMENT: "납부", OTHER: "기타" };
export default async function SchedulesPage({ searchParams }: { searchParams: Promise<{ homeId?: string | string[] }> }) { const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login"); const query = await searchParams; const requestedHomeId = typeof query.homeId === "string" ? query.homeId : undefined; const data = await listAllSchedules(session.user.id, requestedHomeId); return <main className={styles.page}><div className={styles.shell}><RecordPageHeader eyebrow="ALL HOME SCHEDULES" title="일정" description="모든 집의 점검·계약·납부 일정을 한곳에서 확인하세요." actionHref={data.homes.length ? "/schedules/new" : undefined} actionLabel="일정 등록" /><AllHomesFilter homes={data.homes} activeHomeId={data.homeId} basePath="/schedules" />{!data.homes.length ? <section className={styles.empty}><span>🏡</span><h2>먼저 주거공간을 등록해 주세요</h2><p>집을 등록하면 일정을 관리할 수 있습니다.</p><Link className={styles.primary} href="/home/new">내 집 등록하기</Link></section> : data.schedules.length ? <section className={styles.grid} aria-label="일정 목록">{data.schedules.map((schedule) => <Link className={styles.card} href={`/homes/${schedule.homeId}/schedules/${schedule.id}`} key={schedule.id}><div className={styles.cardTop}><span className={styles.badge}>{labels[schedule.type]}</span><span className={styles.status}>{schedule.completed ? "완료" : "예정"}</span></div><h2>{schedule.title}</h2><p className={styles.homeName}><span>🏠</span>{schedule.home.name}</p><p className={styles.meta}>{schedule.scheduledAt.toLocaleString("ko-KR")}{schedule.homeItem ? ` · ${schedule.homeItem.name}` : ""}</p></Link>)}</section> : <section className={styles.empty}><span>📅</span><h2>아직 등록된 일정이 없습니다</h2><p>점검과 납부 같은 중요한 일정을 등록해보세요.</p><Link className={styles.primary} href="/schedules/new">첫 일정 등록</Link></section>}</div></main>; }
