import { getServerSession } from "next-auth";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AllHomesFilter } from "@/components/home/all-homes-filter";
import { RecordPageHeader } from "@/components/home/record-page-header";
import { authOptions } from "@/lib/auth/options";
import { listAllExpenses } from "@/lib/home-expense/service";
import styles from "@/app/items/items.module.css";
const labels = { PURCHASE: "구매", REPAIR: "수리", MAINTENANCE: "유지관리", MANAGEMENT: "관리비", UTILITY: "공과금", CONTRACT: "계약관련", INSURANCE: "보험", TAX: "세금", OTHER: "기타" };
export default async function ExpensesPage({ searchParams }: { searchParams: Promise<{ homeId?: string | string[]; period?: string | string[] }> }) { const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login"); const query = await searchParams; const requestedHomeId = typeof query.homeId === "string" ? query.homeId : undefined; const period = query.period === "year" || query.period === "all" ? query.period : "month"; const data = await listAllExpenses(session.user.id, requestedHomeId, period); const periodHref = (value: string) => `${value === "month" ? "/expenses" : `/expenses?period=${value}`}${data.homeId ? `${value === "month" ? "?" : "&"}homeId=${data.homeId}` : ""}`; return <main className={styles.page}><div className={styles.shell}><RecordPageHeader eyebrow="ALL HOME EXPENSES" title="비용" description="모든 집의 구매·수리·관리 지출을 한곳에서 확인하세요." actionHref={data.homes.length ? "/expenses/new" : undefined} actionLabel="비용 등록" /><AllHomesFilter homes={data.homes} activeHomeId={data.homeId} basePath="/expenses" query={{ period: data.period === "month" ? undefined : data.period }} /><nav className={styles.periods} aria-label="비용 기간"><Link className={period === "month" ? styles.activePeriod : undefined} href={periodHref("month")}>이번 달</Link><Link className={period === "year" ? styles.activePeriod : undefined} href={periodHref("year")}>올해</Link><Link className={period === "all" ? styles.activePeriod : undefined} href={periodHref("all")}>전체</Link></nav>{!data.homes.length ? <section className={styles.empty}><span>🏡</span><h2>먼저 주거공간을 등록해 주세요</h2><p>집을 등록하면 비용을 관리할 수 있습니다.</p><Link className={styles.primary} href="/home/new">내 집 등록하기</Link></section> : <><section className={styles.summaryPanel}><p>선택 기간 총 지출</p><strong>{data.total.toLocaleString("ko-KR")}원</strong>{data.summary.length ? <div>{data.summary.map((row) => <span key={row.category}>{labels[row.category]} {Number(row.amount).toLocaleString("ko-KR")}원</span>)}</div> : null}</section>{data.expenses.length ? <section className={styles.grid} aria-label="비용 목록">{data.expenses.map((expense) => <Link className={styles.card} href={`/homes/${expense.homeId}/expenses/${expense.id}`} key={expense.id}><div className={styles.cardTop}><span className={styles.badge}>{labels[expense.category]}</span><span className={styles.status}>{Number(expense.amount).toLocaleString("ko-KR")}원</span></div><h2>{expense.title}</h2><p className={styles.homeName}><span>🏠</span>{expense.home.name}</p><p className={styles.meta}>{expense.expenseDate.toLocaleDateString("ko-KR")}{expense.homeItem ? ` · ${expense.homeItem.name}` : ""}</p></Link>)}</section> : <section className={styles.empty}><span>💰</span><h2>선택한 기간의 비용 기록이 없습니다</h2><p>집과 관련된 지출을 기록해보세요.</p><Link className={styles.primary} href="/expenses/new">첫 비용 등록</Link></section>}</>}</div></main>; }
