"use client";
import { FormEvent, useRef, useState } from "react";
import styles from "./address-field.module.css";
type AddressResult = { roadAddr: string; jibunAddr: string; zipNo: string; buildingName: string };
export function AddressField({ defaultValue = "", error }: { defaultValue?: string; error?: string }) {
  const [address, setAddress] = useState(defaultValue), [open, setOpen] = useState(false), [keyword, setKeyword] = useState(""), [results, setResults] = useState<AddressResult[]>([]), [message, setMessage] = useState(""), [pending, setPending] = useState(false); const searchInput = useRef<HTMLInputElement>(null);
  function toggleSearch() { setOpen((current) => !current); setMessage(""); setTimeout(() => searchInput.current?.focus(), 0); }
  async function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const query = keyword.trim(); if (query.length < 2) { setMessage("도로명, 건물명 또는 지번을 2자 이상 입력해 주세요."); return; } setPending(true); setMessage(""); try { const response = await fetch(`/api/address/search?keyword=${encodeURIComponent(query)}`), data = await response.json(); if (!response.ok) { setResults([]); setMessage(data.message ?? "주소를 검색하지 못했습니다. 직접 입력해 주세요."); return; } setResults(data.addresses); if (!data.addresses.length) setMessage("검색 결과가 없습니다. 검색어를 확인하거나 주소를 직접 입력해 주세요."); } catch { setResults([]); setMessage("주소 검색 서비스에 연결할 수 없습니다. 주소를 직접 입력해 주세요."); } finally { setPending(false); } }
  function selectAddress(result: AddressResult) { setAddress(result.roadAddr); setOpen(false); setResults([]); setMessage(""); requestAnimationFrame(() => document.getElementById("address-detail")?.focus()); }
  return <div className={styles.field}><label htmlFor="address">주소</label><div className={styles.inputRow}><input id="address" name="address" value={address} onChange={(event) => setAddress(event.target.value)} maxLength={200} required aria-describedby={error ? "address-error" : "address-help"}/><button type="button" onClick={toggleSearch} aria-expanded={open} aria-controls="address-search-panel">주소 검색</button></div><p id={error ? "address-error" : "address-help"} className={error ? styles.error : undefined}>{error ?? "도로명주소를 검색하거나 직접 입력할 수 있습니다. 상세주소는 아래에 따로 입력해 주세요."}</p>{open && <section id="address-search-panel" className={styles.panel} aria-label="도로명주소 검색"><form className={styles.searchForm} onSubmit={search} role="search"><label htmlFor="address-keyword">도로명주소 검색어</label><div><input ref={searchInput} id="address-keyword" value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="예: 세종대로 110 또는 서울시청" maxLength={100}/><button type="submit" disabled={pending}>{pending ? "검색 중…" : "검색"}</button></div></form><div className={styles.results} aria-live="polite" aria-busy={pending}>{message && <p role="status">{message}</p>}{results.map((result) => <button type="button" key={`${result.roadAddr}-${result.zipNo}`} onClick={() => selectAddress(result)}><strong>{result.roadAddr}</strong><span>{result.jibunAddr}</span><small>우편번호 {result.zipNo}{result.buildingName ? ` · ${result.buildingName}` : ""}</small></button>)}</div><button className={styles.close} type="button" onClick={() => setOpen(false)}>검색 닫기</button></section>}</div>;
}
