import { AttachmentPanel } from "@/components/attachments/attachment-panel";
import { getServerSession } from "next-auth";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { authOptions } from "@/lib/auth/options";
import { getOwnedExpense } from "@/lib/home-expense/service";
import styles from "@/app/homes/[homeId]/items/items.module.css";
const labels: Record<string, string> = { PURCHASE: "구매", REPAIR: "수리", MAINTENANCE: "유지관리", MANAGEMENT: "관리비", UTILITY: "공과금", CONTRACT: "계약관련", INSURANCE: "보험", TAX: "세금", OTHER: "기타" };
export default async function ExpenseDetail({ params }: PageProps<"/homes/[homeId]/expenses/[expenseId]">) { const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login"); const { homeId, expenseId } = await params; const expense = await getOwnedExpense(session.user.id, homeId, expenseId); if (!expense) notFound(); return <main className={styles.page}><div className={styles.shell}><div className={styles.detailActions}><Link className={styles.back} href="/expenses">← 비용 전체 목록</Link><Link className={styles.back} href={`/dashboard?homeId=${homeId}`}>Dashboard</Link></div><nav className={styles.itemTrail} aria-label="비용 위치"><Link href={`/expenses?homeId=${homeId}`}>{expense.home.name}</Link><span>›</span><span>{expense.title}</span></nav><article className={styles.detail}><span className={styles.badge}>{labels[expense.category]}</span><h1>{expense.title}</h1><dl><div><dt>소속 집</dt><dd>{expense.home.name}</dd></div><div><dt>금액</dt><dd>{Number(expense.amount).toLocaleString("ko-KR")}원</dd></div><div><dt>날짜</dt><dd>{expense.expenseDate.toLocaleDateString("ko-KR")}</dd></div><div><dt>결제수단</dt><dd>{expense.paymentMethod ?? "미입력"}</dd></div><div><dt>관련 물건</dt><dd>{expense.homeItem?.name ?? "연결 없음"}</dd></div><div><dt>관련 수리·점검</dt><dd>{expense.repair?.title ?? "연결 없음"}</dd></div><div><dt>개인 메모</dt><dd>{expense.memo ?? "없음"}</dd></div></dl><div className={styles.actions}><Link className={styles.primary} href={`/homes/${homeId}/expenses/${expenseId}/edit`}>비용 수정</Link></div></article><AttachmentPanel target={{ type: "expense", id: expenseId }} /></div></main>; }
