"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import styles from "@/app/homes/[homeId]/items/items.module.css";
const types = { CONTRACT: "계약", WARRANTY: "보증서", RECEIPT: "영수증", MANUAL: "설명서", INSURANCE: "보험", TAX: "세금", CERTIFICATE: "증명서", OTHER: "기타" };
type DocumentValue = { id: string; type: keyof typeof types; title: string; documentNumber: string | null; issuer: string | null; issuedDate: Date | null; expiresAt: Date | null; homeItemId: string | null; contractId: string | null; memo: string | null; status: string };
export function DocumentForm({ homeId, items, contracts, document }: { homeId: string; items: { id: string; name: string }[]; contracts: { id: string; title: string }[]; document?: DocumentValue }) {
  const router = useRouter(), [error, setError] = useState("");
  const date = (value: Date | null) => value ? new Date(value).toISOString().slice(0, 10) : "";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/homes/${homeId}/documents${document ? `/${document.id}` : ""}`, { method: document ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.message); return; } router.push(`/homes/${homeId}/documents/${document?.id ?? result.document.id}`); router.refresh(); }
  return <form className={styles.form} onSubmit={submit}><label htmlFor="title">문서명 *</label><input id="title" name="title" defaultValue={document?.title} maxLength={120} required/><label htmlFor="type">문서 유형 *</label><select id="type" name="type" defaultValue={document?.type ?? "OTHER"}>{Object.entries(types).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><div className={styles.two}><div><label htmlFor="documentNumber">문서번호</label><input id="documentNumber" name="documentNumber" defaultValue={document?.documentNumber ?? ""} maxLength={120}/></div><div><label htmlFor="issuer">발급기관</label><input id="issuer" name="issuer" defaultValue={document?.issuer ?? ""} maxLength={120}/></div></div><div className={styles.two}><div><label htmlFor="issuedDate">발급일</label><input id="issuedDate" name="issuedDate" type="date" defaultValue={date(document?.issuedDate ?? null)}/></div><div><label htmlFor="expiresAt">만료일</label><input id="expiresAt" name="expiresAt" type="date" defaultValue={date(document?.expiresAt ?? null)}/></div></div><label htmlFor="homeItemId">관련 물건</label><select id="homeItemId" name="homeItemId" defaultValue={document?.homeItemId ?? ""}><option value="">연결하지 않음</option>{items.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><label htmlFor="contractId">관련 계약</label><select id="contractId" name="contractId" defaultValue={document?.contractId ?? ""}><option value="">연결하지 않음</option>{contracts.map((contract) => <option value={contract.id} key={contract.id}>{contract.title}</option>)}</select><label htmlFor="status">상태</label><select id="status" name="status" defaultValue={document?.status === "ARCHIVED" ? "ARCHIVED" : "ACTIVE"}><option value="ACTIVE">보관 중</option><option value="ARCHIVED">보관 종료</option></select><label htmlFor="memo">개인 메모</label><textarea id="memo" name="memo" defaultValue={document?.memo ?? ""} maxLength={2000}/><p className={styles.meta}>문서번호, 발급기관, 메모와 만료정보는 커뮤니티나 장터에 공개되지 않습니다. 실제 파일은 아직 저장하지 않습니다.</p>{error && <p className={styles.error} role="alert">{error}</p>}<button className={styles.primary}>{document ? "수정 완료" : "문서 등록"}</button></form>;
}
