import assert from "node:assert/strict";
import {requestServerOcr,type OcrCache} from "../src/lib/product-label/server-ocr-client";
import {extractProductLabel} from "../src/lib/product-label/extract";
let requests=0,decodes=0;const result=extractProductLabel("모델명: TEST-123",95);
globalThis.createImageBitmap=async()=>{decodes++;return {width:2400,height:1800,close(){}} as ImageBitmap;};
const canvas={width:0,height:0,getContext(){return {fillStyle:"",fillRect(){},drawImage(){}};},toBlob(callback:BlobCallback){assert.equal(this.width,1600);assert.equal(this.height,1200);callback(new Blob(["encoded photo"],{type:"image/png"}));}};
Object.defineProperty(globalThis,"document",{value:{createElement(){return canvas;}},configurable:true});
globalThis.fetch=async()=>{requests++;return Response.json({result,durationMs:100,mode:"fast"});};
const cache:OcrCache=new Map(),signal=new AbortController().signal;
const file=new File(["same original photo"],"label.jpg",{type:"image/jpeg"});
assert.equal((await requestServerOcr(file,"fast",signal,cache)).cached,false);
assert.equal((await requestServerOcr(new File(["same original photo"],"another-name.jpg",{type:"image/jpeg"}),"fast",signal,cache)).cached,true);
assert.equal(requests,1);assert.equal(decodes,1);assert.equal(canvas.width,0);
await requestServerOcr(file,"full",signal,cache);assert.equal(requests,2);
globalThis.fetch=async()=>{requests++;return Response.json({error:"수동 입력"},{status:504});};
await assert.rejects(requestServerOcr(new File(["new photo"],"new.jpg",{type:"image/jpeg"}),"fast",signal,cache),/수동 입력/);
assert.equal(requests,3);assert.equal(cache.size,2);
await assert.rejects(requestServerOcr(file,"fast",AbortSignal.abort(),new Map()),/분석 취소/);
assert.equal(requests,3);
console.log("PASS: 1600px pre-upload resize; same-image cache; separate full mode; no failure/abort auto-retry; canvas cleared (mock tests, not real-phone tests)");
