import assert from "node:assert/strict";
import sharp from "sharp";
import { aiConfiguration, sanitizeLabelImage } from "../src/lib/product-label/ai-server";
import { aiLabelSchema, compareLabelResults, validateAiLabel } from "../src/lib/product-label/ai";
import { extractProductLabel } from "../src/lib/product-label/extract";
const empty={value:null,evidence:null};
const base={brand:empty,name:empty,modelName:empty,manufacturedAt:empty,serialNumber:empty,category:empty};
const ai=validateAiLabel({...base,modelName:{value:"S839S30",evidence:"모델명 S839S30"}});
assert.equal(compareLabelResults(extractProductLabel("모델명 :8839830 Bae",65),ai).modelName.agreement,"AI_ONLY");
assert.equal(compareLabelResults(extractProductLabel("모델: S839S30",95),ai).modelName.agreement,"MATCH");
assert.equal(compareLabelResults(extractProductLabel("모델: S839S31",95),ai).modelName.agreement,"DIFFERENT");
assert.equal(validateAiLabel({...base,modelName:{value:"8839830 Bae",evidence:"bad"}}).modelName.value,null);
assert.equal(validateAiLabel({...base,modelName:{value:"S839S30",evidence:null}}).modelName.value,null);
assert.equal(validateAiLabel({...base,manufacturedAt:{value:"2024-02-30",evidence:"bad"}}).manufacturedAt.value,null);
assert.equal(aiLabelSchema.safeParse({...base,email:"private"}).success,false);
assert.equal(aiConfiguration().enabled,false,"Production/local must fail closed regardless of flag");
const source=await sharp({create:{width:64,height:32,channels:3,background:"white"}}).jpeg().withMetadata({orientation:6}).toBuffer();
const cleaned=await sanitizeLabelImage(new File([source],"label.jpg",{type:"image/jpeg"}));
const metadata=await sharp(cleaned).metadata();assert.equal(metadata.exif,undefined);assert.equal(metadata.orientation,undefined);assert.equal(metadata.width,32);assert.equal(metadata.height,64);
console.log("PASS: comparison, unknown/invalid fields, no personal response fields, local/Production disabled, EXIF removal and rotation; zero AI calls");
