import { getPrisma } from "../src/lib/prisma";
import { createOwnedItem, deleteOwnedItem, getOwnedItem, updateOwnedItem } from "../src/lib/home-item/service";
import { createMarketplacePost, updateMarketplaceStatus } from "../src/lib/community/service";

if (!process.env.DATABASE_URL?.includes("127.0.0.1:55432")) throw new Error("격리된 로컬 테스트 DB에서만 실행할 수 있습니다.");
const prisma=getPrisma();
const input={name:"테스트 냉장고",category:"APPLIANCE" as const,brand:"테스트브랜드",modelName:"MODEL-A",purchaseDate:new Date("2024-05-10"),purchasePrice:1800000,warrantyUntil:new Date("2027-05-10"),memo:"장터 비공개 개인 메모",status:"USING" as const};
await prisma.user.createMany({data:[{id:"item-user-a",email:"item-a@example.invalid",passwordHash:"test",nickname:"물건테스트A"},{id:"item-user-b",email:"item-b@example.invalid",passwordHash:"test",nickname:"물건테스트B"}]});
await prisma.home.createMany({data:[{id:"item-home-a",userId:"item-user-a",name:"A의 집",address:"비공개 주소",addressDetail:"101호",housingType:"APARTMENT"},{id:"item-home-b",userId:"item-user-b",name:"B의 집",address:"비공개 주소",addressDetail:"202호",housingType:"APARTMENT"}]});
await prisma.apartment.create({data:{id:"item-apartment",externalCode:"ITEM-TEST",name:"물건 테스트 아파트",sido:"서울특별시",sigungu:"테스트구",roadAddress:"공개 단지 주소",dataSource:"TEST_ONLY"}});
const member=await prisma.apartmentMember.create({data:{userId:"item-user-a",apartmentId:"item-apartment"}});await prisma.apartmentMember.create({data:{userId:"item-user-b",apartmentId:"item-apartment"}});
try{const item=await createOwnedItem("item-user-a","item-home-a",input);if(!item)throw new Error("CREATE 실패");if(await getOwnedItem("item-user-b","item-home-a",item.id))throw new Error("타인 조회 허용");if(await updateOwnedItem("item-user-b","item-home-a",item.id,{...input,name:"침해"}))throw new Error("타인 수정 허용");if(await deleteOwnedItem("item-user-b","item-home-a",item.id))throw new Error("타인 삭제 허용");const updated=await updateOwnedItem("item-user-a","item-home-a",item.id,{...input,name:"수정된 냉장고"});if(updated?.name!=="수정된 냉장고")throw new Error("UPDATE 실패");const invalid=await createMarketplacePost("item-user-b","item-apartment",{type:"SELL",title:"침해",description:"침해",price:1,sourceHomeItemId:item.id});if(invalid)throw new Error("타인 물건 장터 변환 허용");const sell=await prisma.marketplacePost.create({data:{apartmentId:"item-apartment",sellerMemberId:member.id,sourceHomeItemId:item.id,type:"SELL",title:item.name,description:"공개 설명",price:10000}});await updateMarketplaceStatus("item-user-a","item-apartment",sell.id,"COMPLETED");if((await prisma.homeItem.findUnique({where:{id:item.id}}))?.status!=="SOLD")throw new Error("SOLD 연동 실패");const giveawayItem=await createOwnedItem("item-user-a","item-home-a",{...input,name:"나눔 물건"});if(!giveawayItem)throw new Error("나눔 물건 생성 실패");const giveaway=await createMarketplacePost("item-user-a","item-apartment",{type:"GIVEAWAY",title:giveawayItem.name,description:"공개 나눔 설명",price:0,sourceHomeItemId:giveawayItem.id});if(!giveaway)throw new Error("나눔 변환 실패");await updateMarketplaceStatus("item-user-a","item-apartment",giveaway.id,"COMPLETED");if((await prisma.homeItem.findUnique({where:{id:giveawayItem.id}}))?.status!=="GIVEN_AWAY")throw new Error("GIVEN_AWAY 연동 실패");const publicSnapshot=JSON.stringify(await prisma.marketplacePost.findMany({select:{title:true,description:true,price:true,status:true,sellerMember:{select:{user:{select:{nickname:true}}}},apartment:{select:{name:true}}}}));for(const forbidden of ["비공개 개인 메모","비공개 주소","101호","email","passwordHash","purchasePrice","warrantyUntil"])if(publicSnapshot.includes(forbidden))throw new Error(`개인정보 노출: ${forbidden}`);console.log(JSON.stringify({crud:"PASS",homeOwnership:"PASS",marketplaceOwnership:"PASS",sellToSold:"PASS",giveawayToGivenAway:"PASS",privacySnapshot:"PASS"}))}finally{await prisma.user.deleteMany({where:{id:{in:["item-user-a","item-user-b"]}}});await prisma.apartment.deleteMany({where:{id:"item-apartment"}});await prisma.$disconnect()}
