import { AttachmentPanel } from "@/components/attachments/attachment-panel";
import { getServerSession } from "next-auth";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { authOptions } from "@/lib/auth/options";
import { derivedDocumentStatus, getOwnedDocument } from "@/lib/home-document/service";
import styles from "@/app/homes/[homeId]/items/items.module.css";
const types: Record<string, string> = { CONTRACT: "계약", WARRANTY: "보증서", RECEIPT: "영수증", MANUAL: "설명서", INSURANCE: "보험", TAX: "세금", CERTIFICATE: "증명서", OTHER: "기타" }, statuses: Record<string, string> = { ACTIVE: "보관 중", EXPIRED: "만료", ARCHIVED: "보관 종료" };
export default async function DocumentDetailPage({ params }: PageProps<"/homes/[homeId]/documents/[documentId]">) { const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login"); const { homeId, documentId } = await params; const document = await getOwnedDocument(session.user.id, homeId, documentId); if (!document) notFound(); const state = derivedDocumentStatus(document); return <main className={styles.page}><div className={styles.shell}><div className={styles.detailActions}><Link className={styles.back} href="/documents">← 문서 전체 목록</Link><Link className={styles.back} href={`/dashboard?homeId=${homeId}`}>Dashboard</Link></div><nav className={styles.itemTrail} aria-label="문서 위치"><Link href={`/documents?homeId=${homeId}`}>{document.home.name}</Link><span>›</span><span>{document.title}</span></nav><article className={styles.detail}><span className={styles.badge}>{types[document.type]} · {statuses[state]}</span><h1>{document.title}</h1><dl><div><dt>소속 집</dt><dd>{document.home.name}</dd></div><div><dt>문서번호</dt><dd>{document.documentNumber ?? "미입력"}</dd></div><div><dt>발급기관</dt><dd>{document.issuer ?? "미입력"}</dd></div><div><dt>발급일</dt><dd>{document.issuedDate?.toLocaleDateString("ko-KR") ?? "미입력"}</dd></div><div><dt>만료일</dt><dd>{document.expiresAt?.toLocaleDateString("ko-KR") ?? "미입력"}</dd></div><div><dt>관련 물건</dt><dd>{document.homeItem?.name ?? "연결 없음"}</dd></div><div><dt>관련 계약</dt><dd>{document.contract?.title ?? "연결 없음"}</dd></div></dl>{document.memo && <p className={styles.notice}>{document.memo}</p>}<div className={styles.actions}><Link className={styles.primary} href={`/homes/${homeId}/documents/${documentId}/edit`}>문서 수정</Link></div></article><AttachmentPanel target={{ type: "document", id: documentId }} /></div></main>; }
