import { Prisma } from "@/generated/prisma/client";
import { getPrisma } from "@/lib/prisma";
import type { ExpenseInput } from "./validation";
async function ownedHome(userId:string,homeId:string){return getPrisma().home.findFirst({where:{id:homeId,userId},select:{id:true,name:true}})}
async function validRelations(userId:string,homeId:string,itemId:string|null,repairId:string|null){const[item,repair]=await Promise.all([itemId?getPrisma().homeItem.findFirst({where:{id:itemId,homeId,home:{userId}},select:{id:true}}):true,repairId?getPrisma().homeRepair.findFirst({where:{id:repairId,homeId,home:{userId}},select:{id:true,homeItemId:true}}):true]);if(!item||!repair)return false;if(itemId&&repairId&&typeof repair!=="boolean"&&repair.homeItemId&&repair.homeItemId!==itemId)return false;return true}
const data=(input:ExpenseInput)=>({...input,amount:new Prisma.Decimal(input.amount)});
export async function listExpenses(userId:string,homeId:string,period:"month"|"year"|"all"="month"){const home=await ownedHome(userId,homeId);if(!home)return null;const now=new Date();const from=period==="month"?new Date(now.getFullYear(),now.getMonth(),1):period==="year"?new Date(now.getFullYear(),0,1):undefined;const prisma=getPrisma();const[items,repairs,expenses,grouped]=await Promise.all([prisma.homeItem.findMany({where:{homeId},select:{id:true,name:true},orderBy:{name:"asc"}}),prisma.homeRepair.findMany({where:{homeId},select:{id:true,title:true,homeItemId:true},orderBy:{repairDate:"desc"}}),prisma.homeExpense.findMany({where:{homeId,...(from?{expenseDate:{gte:from}}:{})},include:{homeItem:{select:{name:true}},repair:{select:{title:true}}},orderBy:{expenseDate:"desc"}}),prisma.homeExpense.groupBy({by:["category"],where:{homeId,...(from?{expenseDate:{gte:from}}:{})},_sum:{amount:true}})]);return{home,items,repairs,expenses,summary:grouped.map(row=>({category:row.category,amount:row._sum.amount??new Prisma.Decimal(0)})),total:grouped.reduce((sum,row)=>sum+Number(row._sum.amount??0),0),period}}
export async function createExpense(userId:string,homeId:string,input:ExpenseInput,sourceKey:string|null=null){if(!await ownedHome(userId,homeId)||!await validRelations(userId,homeId,input.homeItemId,input.repairId))return null;try{return await getPrisma().homeExpense.create({data:{...data(input),homeId,sourceKey}})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return "duplicate" as const;throw error}}
export function getOwnedExpense(userId:string,homeId:string,id:string){return getPrisma().homeExpense.findFirst({where:{id,homeId,home:{userId}},include:{homeItem:{select:{id:true,name:true}},repair:{select:{id:true,title:true}}}})}
export async function updateExpense(userId:string,homeId:string,id:string,input:ExpenseInput){if(!await validRelations(userId,homeId,input.homeItemId,input.repairId))return null;const result=await getPrisma().homeExpense.updateMany({where:{id,homeId,home:{userId}},data:data(input)});return result.count?getOwnedExpense(userId,homeId,id):null}
export async function deleteExpense(userId:string,homeId:string,id:string){return(await getPrisma().homeExpense.deleteMany({where:{id,homeId,home:{userId}}})).count===1}
export async function expenseTotals(userId:string){const now=new Date(),month=new Date(now.getFullYear(),now.getMonth(),1),year=new Date(now.getFullYear(),0,1);const prisma=getPrisma();const[monthRows,yearRows]=await Promise.all([prisma.homeExpense.aggregate({where:{home:{userId},expenseDate:{gte:month}},_sum:{amount:true}}),prisma.homeExpense.aggregate({where:{home:{userId},expenseDate:{gte:year}},_sum:{amount:true}})]);return{month:Number(monthRows._sum.amount??0),year:Number(yearRows._sum.amount??0)}}
