import { getServerSession } from "next-auth";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AllHomesFilter } from "@/components/home/all-homes-filter";
import { RecordPageHeader } from "@/components/home/record-page-header";
import { authOptions } from "@/lib/auth/options";
import { derivedDocumentStatus, listAllDocuments } from "@/lib/home-document/service";
import styles from "@/app/items/items.module.css";
const types = { CONTRACT: "계약서", WARRANTY: "보증서", RECEIPT: "영수증", MANUAL: "설명서", INSURANCE: "보험", TAX: "세금", CERTIFICATE: "증명서", OTHER: "기타" }; const statuses = { ACTIVE: "보관 중", EXPIRED: "만료", ARCHIVED: "보관 종료" };
export default async function DocumentsPage({ searchParams }: { searchParams: Promise<{ homeId?: string | string[] }> }) { const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login"); const query = await searchParams; const requestedHomeId = typeof query.homeId === "string" ? query.homeId : undefined; const data = await listAllDocuments(session.user.id, requestedHomeId); return <main className={styles.page}><div className={styles.shell}><RecordPageHeader eyebrow="ALL HOME DOCUMENTS" title="문서" description="모든 집의 계약서·보증서·영수증 정보를 한곳에서 관리하세요." actionHref={data.homes.length ? "/documents/new" : undefined} actionLabel="문서 등록" /><AllHomesFilter homes={data.homes} activeHomeId={data.homeId} basePath="/documents" />{!data.homes.length ? <section className={styles.empty}><span>🏡</span><h2>먼저 주거공간을 등록해 주세요</h2><p>집을 등록하면 문서를 관리할 수 있습니다.</p><Link className={styles.primary} href="/home/new">내 집 등록하기</Link></section> : data.documents.length ? <section className={styles.grid} aria-label="문서 목록">{data.documents.map((document) => { const state = derivedDocumentStatus(document); return <Link className={styles.card} href={`/homes/${document.homeId}/documents/${document.id}`} key={document.id}><div className={styles.cardTop}><span className={styles.badge}>{types[document.type]}</span><span className={styles.status}>{statuses[state]}</span></div><h2>{document.title}</h2><p className={styles.homeName}><span>🏠</span>{document.home.name}</p><p className={styles.meta}>{document.expiresAt ? `${document.expiresAt.toLocaleDateString("ko-KR")} 만료` : "만료일 미입력"}</p></Link>; })}</section> : <section className={styles.empty}><span>📄</span><h2>아직 보관된 문서가 없습니다</h2><p>계약서와 보증서의 정보를 기록해보세요.</p><Link className={styles.primary} href="/documents/new">첫 문서 등록</Link></section>}</div></main>; }
